# Generated by Django 6.0.3 on 2026-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('cesantias', models.FloatField(blank=True, null=True)),
                ('intereses', models.FloatField(blank=True, null=True)),
                ('prima', models.FloatField(blank=True, null=True)),
                ('vacaciones', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
